import { useState } from "react";
import { X } from "lucide-react";

export function WhyAmISeeingThisModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/40 p-4" onClick={onClose}>
      <div className="bg-card rounded-2xl max-w-md w-full p-5" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between">
          <h3 className="text-base font-semibold text-primary">Why am I seeing this?</h3>
          <button onClick={onClose} aria-label="Close"><X size={18} color="#8FA8B8" /></button>
        </div>
        <p className="mt-3 text-sm leading-relaxed" style={{ color: "#F0EDDE" }}>
          This recommendation is generated by analyzing the last 14 days of your logs. We use your data to surface the
          product most aligned with your current pattern. You can dismiss this card or ignore it — your journey
          continues either way. We never share your data with third parties.
        </p>
        <button onClick={onClose} className="mt-5 w-full h-10 rounded-md bg-primary text-primary-foreground font-semibold text-sm">
          Got it
        </button>
      </div>
    </div>
  );
}

export function useWhyModal() {
  const [open, setOpen] = useState(false);
  return { open, setOpen };
}
