/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingBaselineRouteImport } from './routes/onboarding.baseline'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppLogRouteImport } from './routes/app.log'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppBaselineRouteImport } from './routes/app.baseline'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppCoachGuideIdRouteImport } from './routes/app.coach.guide.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingBaselineRoute = OnboardingBaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppBaselineRoute = AppBaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AppCoachGuideIdRoute = AppCoachGuideIdRouteImport.update({
  id: '/guide/$id',
  path: '/guide/$id',
  getParentRoute: () => AppCoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/baseline': typeof AppBaselineRoute
  '/app/coach': typeof AppCoachRouteWithChildren
  '/app/log': typeof AppLogRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboarding/baseline': typeof OnboardingBaselineRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/coach/guide/$id': typeof AppCoachGuideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/baseline': typeof AppBaselineRoute
  '/app/coach': typeof AppCoachRouteWithChildren
  '/app/log': typeof AppLogRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboarding/baseline': typeof OnboardingBaselineRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/coach/guide/$id': typeof AppCoachGuideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/baseline': typeof AppBaselineRoute
  '/app/coach': typeof AppCoachRouteWithChildren
  '/app/log': typeof AppLogRoute
  '/app/progress': typeof AppProgressRoute
  '/app/settings': typeof AppSettingsRoute
  '/onboarding/baseline': typeof OnboardingBaselineRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/coach/guide/$id': typeof AppCoachGuideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/app/baseline'
    | '/app/coach'
    | '/app/log'
    | '/app/progress'
    | '/app/settings'
    | '/onboarding/baseline'
    | '/admin/'
    | '/app/'
    | '/app/coach/guide/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/app/baseline'
    | '/app/coach'
    | '/app/log'
    | '/app/progress'
    | '/app/settings'
    | '/onboarding/baseline'
    | '/admin'
    | '/app'
    | '/app/coach/guide/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/app/baseline'
    | '/app/coach'
    | '/app/log'
    | '/app/progress'
    | '/app/settings'
    | '/onboarding/baseline'
    | '/admin/'
    | '/app/'
    | '/app/coach/guide/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/baseline': {
      id: '/onboarding/baseline'
      path: '/baseline'
      fullPath: '/onboarding/baseline'
      preLoaderRoute: typeof OnboardingBaselineRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log': {
      id: '/app/log'
      path: '/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/baseline': {
      id: '/app/baseline'
      path: '/baseline'
      fullPath: '/app/baseline'
      preLoaderRoute: typeof AppBaselineRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/coach/guide/$id': {
      id: '/app/coach/guide/$id'
      path: '/guide/$id'
      fullPath: '/app/coach/guide/$id'
      preLoaderRoute: typeof AppCoachGuideIdRouteImport
      parentRoute: typeof AppCoachRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCoachRouteChildren {
  AppCoachGuideIdRoute: typeof AppCoachGuideIdRoute
}

const AppCoachRouteChildren: AppCoachRouteChildren = {
  AppCoachGuideIdRoute: AppCoachGuideIdRoute,
}

const AppCoachRouteWithChildren = AppCoachRoute._addFileChildren(
  AppCoachRouteChildren,
)

interface AppRouteChildren {
  AppBaselineRoute: typeof AppBaselineRoute
  AppCoachRoute: typeof AppCoachRouteWithChildren
  AppLogRoute: typeof AppLogRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBaselineRoute: AppBaselineRoute,
  AppCoachRoute: AppCoachRouteWithChildren,
  AppLogRoute: AppLogRoute,
  AppProgressRoute: AppProgressRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingBaselineRoute: typeof OnboardingBaselineRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBaselineRoute: OnboardingBaselineRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
